server:
  port: 8082

spring:
  application:
    name: ms-marketing-biblioteca

  datasource:
    url: jdbc:mysql://localhost:3306/db_marketing_biblioteca?createDatabaseIfNotExist=true
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    baseline-on-migrate: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html