server:
  port: 0
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /marketing/api-docs
  packages-to-scan: tiendavideojuegos.juegos.controller

  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

spring:
  application:
    name: ms-marketing-biblioteca

  datasource:
    url: jdbc:mysql://localhost:3306/db_marketing_biblioteca?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  mvc:
    cors:
      mappings:
        "/**":
          allowed-origin-patterns: "*"
          allowed-methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
          allowed-headers: "*"
          exposed-headers: "*"
          allow-credentials: false
          max-age: 3600