server:
  port: 8080


spring:
  application:
    name: api-gateway


  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ms-catalogo-videojuegos
              uri: lb://ms-catalogo-videojuegos
              predicates:
                - Path=/api/v1/videojuegos/**

            - id: ms-marketing-biblioteca
              uri: lb://ms-marketing-biblioteca
              predicates:
                - Path=/api/v1/marketing/**
            
            - id: ms-ventas-pagos
              uri: lb://ms-ventas-pagos
              predicates:
                - Path=/api/v1/pagos/**
